-- SQL to insert staff data into nabh_team_members
-- Matches EXACT schema provided: id, name, role, designation, department, responsibilities, is_active, created_at, updated_at

INSERT INTO public.nabh_team_members 
(name, role, designation, department, responsibilities, is_active)
VALUES
('Gaurav Agrawal', 'Management', 'HR Head / Admin', 'Admin', '{}', true),
('Shashank Upgade', 'Support Staff', 'HR Attendant', 'Admin', '{}', true),
('Aman Rajak', 'Safety Officer', 'Fire Safety Officer', 'Safety', '{}', true),
('Roma Kangwani', 'Technical Staff', 'Physiotherapist', 'Physiotherapy', '{}', true),
('Ayushi Nandagawali', 'Support Staff', 'Physiotherapist Attendant', 'Physiotherapy', '{}', true),
('Nitin Bawane', 'Technical Staff', 'X-Ray Technician', 'Radiology', '{}', true),
('Pratik Vyankat', 'Support Staff', 'X-Ray Technician Attendant', 'Radiology', '{}', true),
('Apeksha Wandre', 'Technical Staff', 'OT Technician', 'OT', '{}', true),
('Shruti Uikey', 'Technical Staff', 'OT Technician', 'OT', '{}', true),
('Sarvesh Bhramhe', 'Technical Staff', 'OT Technician', 'OT', '{}', true),
('Digesh Bisen', 'Technical Staff', 'Lab Technician', 'Laboratory', '{}', true),
('Rachana Rathore', 'Technical Staff', 'Lab Technician', 'Laboratory', '{}', true),
('Sarita Rangari', 'Support Staff', 'Lab Attendant', 'Laboratory', '{}', true),
('Nisha Sharma', 'Admin', 'Receptionist', 'Front Office', '{}', true),
('Diksha Sakhare', 'Admin', 'Receptionist', 'Front Office', '{}', true),
('Ruchika Jambhulkar', 'Pharmacy', 'Pharmacist', 'Pharmacy', '{}', true),
('Tejash Akhare', 'Pharmacy', 'Pharmacist', 'Pharmacy', '{}', true),
('Abhishek Dannar', 'Pharmacy', 'Pharmacist', 'Pharmacy', '{}', true),
('Lalit Meshram', 'Support Staff', 'Attendant Pharmacist', 'Pharmacy', '{}', true),
('Jagruti Tembhare', 'Admin', 'Billing Staff', 'Billing', '{}', true),
('Azhar Khan', 'Admin', 'Billing Staff', 'Billing', '{}', true),
('Madhuri Marwate', 'Admin', 'Billing Staff', 'Billing', '{}', true),
('Pragati Nandeshwar', 'Admin', 'Billing Staff', 'Billing', '{}', true),
('Kashish Jagwani', 'Support Staff', 'MRD Attendant', 'MRD', '{}', true),
('Priyanka Tandekar', 'Admin', 'Accountant', 'Finance', '{}', true),
('Shailesh Ninawe', 'Admin', 'Accountant', 'Finance', '{}', true),
('Reena Nirgule', 'Support Staff', 'House-Keeping Supervisor', 'Housekeeping', '{}', true),
('Asha Sakhare', 'Support Staff', 'Aya', 'Housekeeping', '{}', true),
('Urmila Lautkar', 'Support Staff', 'Aya', 'Housekeeping', '{}', true),
('Shubhangi Naik', 'Support Staff', 'Aya', 'Housekeeping', '{}', true),
('Shrushti Lendare', 'Support Staff', 'Aya', 'Housekeeping', '{}', true),
('Shilpa Bankar', 'Support Staff', 'Aya', 'Housekeeping', '{}', true),
('Karuna Dhupare', 'Support Staff', 'Aya', 'Housekeeping', '{}', true),
('Usha Bhave', 'Support Staff', 'Aya', 'Housekeeping', '{}', true),
('Kartik Jangade', 'Support Staff', 'Wardboy', 'Housekeeping', '{}', true),
('Vivek Channe', 'Support Staff', 'Wardboy', 'Housekeeping', '{}', true),
('Rajkumar Walake', 'Support Staff', 'Housekeeping', 'Housekeeping', '{}', true),
('Vijay Chatpaliwar', 'Support Staff', 'Housekeeping', 'Housekeeping', '{}', true),
('Janardhan Motghare', 'Support Staff', 'Housekeeping', 'Housekeeping', '{}', true),
('Afroz Khan', 'Support Staff', 'Security Guard', 'Security', '{}', true),
('Kiran Kadbe', 'Support Staff', 'Security Guard', 'Security', '{}', true),
('Jiyalal Sukhdeve', 'Support Staff', 'Security Guard', 'Security', '{}', true);
