export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      nabh_chapters: {
        Row: {
          id: string;
          chapter_number: number;
          name: string;
          description: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          chapter_number: number;
          name: string;
          description?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          chapter_number?: number;
          name?: string;
          description?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      nabh_standards: {
        Row: {
          id: string;
          chapter_id: string;
          standard_number: string;
          name: string;
          description: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          chapter_id: string;
          standard_number: string;
          name: string;
          description?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          chapter_id?: string;
          standard_number?: string;
          name?: string;
          description?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      nabh_objective_elements: {
        Row: {
          id: string;
          standard_id: string;
          element_number: string;
          description: string;
          hindi_explanation: string | null;
          interpretation: string | null;
          is_core: boolean;
          status: 'Not Started' | 'In Progress' | 'Completed' | 'Not Applicable';
          assignee: string | null;
          evidence_links: string | null;
          youtube_videos: Json | null;
          notes: string | null;
          infographic_svg: string | null;
          infographic_data_url: string | null;
          infographic_created_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          standard_id: string;
          element_number: string;
          description: string;
          hindi_explanation?: string | null;
          interpretation?: string | null;
          is_core?: boolean;
          status?: 'Not Started' | 'In Progress' | 'Completed' | 'Not Applicable';
          assignee?: string | null;
          evidence_links?: string | null;
          youtube_videos?: Json | null;
          notes?: string | null;
          infographic_svg?: string | null;
          infographic_data_url?: string | null;
          infographic_created_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          standard_id?: string;
          element_number?: string;
          description?: string;
          hindi_explanation?: string | null;
          interpretation?: string | null;
          is_core?: boolean;
          status?: 'Not Started' | 'In Progress' | 'Completed' | 'Not Applicable';
          assignee?: string | null;
          evidence_links?: string | null;
          youtube_videos?: Json | null;
          notes?: string | null;
          infographic_svg?: string | null;
          infographic_data_url?: string | null;
          infographic_created_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      nabh_evidence_files: {
        Row: {
          id: string;
          element_id: string;
          file_name: string;
          file_type: 'image' | 'pdf';
          file_size: number;
          file_url: string;
          uploaded_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          element_id: string;
          file_name: string;
          file_type: 'image' | 'pdf';
          file_size: number;
          file_url: string;
          uploaded_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          element_id?: string;
          file_name?: string;
          file_type?: 'image' | 'pdf';
          file_size?: number;
          file_url?: string;
          uploaded_by?: string | null;
          created_at?: string;
        };
      };
      nabh_ai_generated_evidence: {
        Row: {
          id: string;
          element_id: string | null;
          objective_code: string | null;
          evidence_title: string | null;
          prompt: string;
          generated_content: string;
          html_content: string | null;
          evidence_type: 'document' | 'visual' | 'custom' | 'register';
          visual_type: string | null;
          image_url: string | null;
          language: string | null;
          hospital_config: Json | null;
          is_auditor_ready: boolean | null;
          created_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          element_id?: string | null;
          objective_code?: string | null;
          evidence_title?: string | null;
          prompt: string;
          generated_content: string;
          html_content?: string | null;
          evidence_type: 'document' | 'visual' | 'custom' | 'register';
          visual_type?: string | null;
          image_url?: string | null;
          language?: string | null;
          hospital_config?: Json | null;
          is_auditor_ready?: boolean | null;
          created_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          element_id?: string | null;
          objective_code?: string | null;
          evidence_title?: string | null;
          prompt?: string;
          generated_content?: string;
          html_content?: string | null;
          evidence_type?: 'document' | 'visual' | 'custom' | 'register';
          visual_type?: string | null;
          image_url?: string | null;
          language?: string | null;
          hospital_config?: Json | null;
          is_auditor_ready?: boolean | null;
          created_by?: string | null;
          created_at?: string;
        };
      };
      nabh_team_members: {
        Row: {
          id: string;
          name: string;
          role: string;
          designation: string;
          department: string;
          responsibilities: string[] | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          role: string;
          designation: string;
          department: string;
          responsibilities?: string[] | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          role?: string;
          designation?: string;
          department?: string;
          responsibilities?: string[] | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      nabh_audit_log: {
        Row: {
          id: string;
          table_name: string;
          record_id: string;
          action: 'INSERT' | 'UPDATE' | 'DELETE';
          old_data: Json | null;
          new_data: Json | null;
          user_id: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          table_name: string;
          record_id: string;
          action: 'INSERT' | 'UPDATE' | 'DELETE';
          old_data?: Json | null;
          new_data?: Json | null;
          user_id?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          table_name?: string;
          record_id?: string;
          action?: 'INSERT' | 'UPDATE' | 'DELETE';
          old_data?: Json | null;
          new_data?: Json | null;
          user_id?: string | null;
          created_at?: string;
        };
      };
      nabh_infographics: {
        Row: {
          id: string;
          element_id: string;
          svg_content: string;
          data_url: string | null;
          language: 'english' | 'hindi' | 'bilingual';
          version: number;
          is_current: boolean;
          created_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          element_id: string;
          svg_content: string;
          data_url?: string | null;
          language?: 'english' | 'hindi' | 'bilingual';
          version?: number;
          is_current?: boolean;
          created_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          element_id?: string;
          svg_content?: string;
          data_url?: string | null;
          language?: 'english' | 'hindi' | 'bilingual';
          version?: number;
          is_current?: boolean;
          created_by?: string | null;
          created_at?: string;
        };
      };
      nabh_objective_edits: {
        Row: {
          id: string;
          objective_code: string;
          chapter_id: string;
          title: string | null;
          description: string | null;
          hindi_explanation: string | null;
          evidences_list: string | null;
          evidence_links: string | null;
          status: string | null;
          priority: string | null;
          assignee: string | null;
          start_date: string | null;
          end_date: string | null;
          deliverable: string | null;
          notes: string | null;
          infographic_svg: string | null;
          infographic_data_url: string | null;
          evidence_files: Json | null;
          youtube_videos: Json | null;
          training_materials: Json | null;
          sop_documents: Json | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          objective_code: string;
          chapter_id: string;
          title?: string | null;
          description?: string | null;
          hindi_explanation?: string | null;
          evidences_list?: string | null;
          evidence_links?: string | null;
          status?: string | null;
          priority?: string | null;
          assignee?: string | null;
          start_date?: string | null;
          end_date?: string | null;
          deliverable?: string | null;
          notes?: string | null;
          infographic_svg?: string | null;
          infographic_data_url?: string | null;
          evidence_files?: Json | null;
          youtube_videos?: Json | null;
          training_materials?: Json | null;
          sop_documents?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          objective_code?: string;
          chapter_id?: string;
          title?: string | null;
          description?: string | null;
          hindi_explanation?: string | null;
          evidences_list?: string | null;
          evidence_links?: string | null;
          status?: string | null;
          priority?: string | null;
          assignee?: string | null;
          start_date?: string | null;
          end_date?: string | null;
          deliverable?: string | null;
          notes?: string | null;
          infographic_svg?: string | null;
          infographic_data_url?: string | null;
          evidence_files?: Json | null;
          youtube_videos?: Json | null;
          training_materials?: Json | null;
          sop_documents?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      nabh_patients: {
        Row: {
          id: string;
          sr_no: number | null;
          visit_id: string;
          patient_name: string;
          diagnosis: string | null;
          admission_date: string | null;
          discharge_date: string | null;
          status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          sr_no?: number | null;
          visit_id: string;
          patient_name: string;
          diagnosis?: string | null;
          admission_date?: string | null;
          discharge_date?: string | null;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          sr_no?: number | null;
          visit_id?: string;
          patient_name?: string;
          diagnosis?: string | null;
          admission_date?: string | null;
          discharge_date?: string | null;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      rmo_doctors: {
        Row: {
          id: string;
          sr_no: number;
          emp_id_no: string;
          name: string;
          qualification: string;
          designation: string;
          registration_no: string | null;
          doctor_type: string;
          hospital_id: string;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          sr_no: number;
          emp_id_no: string;
          name: string;
          qualification: string;
          designation: string;
          registration_no?: string | null;
          doctor_type?: string;
          hospital_id?: string;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          sr_no?: number;
          emp_id_no?: string;
          name?: string;
          qualification?: string;
          designation?: string;
          registration_no?: string | null;
          doctor_type?: string;
          hospital_id?: string;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      visiting_consultants: {
        Row: {
          id: string;
          sr_no: number;
          name: string;
          department: string;
          qualification: string | null;
          registration_no: string | null;
          registered_council: string;
          hospital_id: string;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          sr_no: number;
          name: string;
          department: string;
          qualification?: string | null;
          registration_no?: string | null;
          registered_council?: string;
          hospital_id?: string;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          sr_no?: number;
          name?: string;
          department?: string;
          qualification?: string | null;
          registration_no?: string | null;
          registered_council?: string;
          hospital_id?: string;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      committees: {
        Row: {
          id: string;
          name: string;
          type: string;
          description: string | null;
          meeting_frequency: string;
          objectives: string[] | null;
          min_meetings_required: number;
          chairperson_id: string | null;
          chairperson_name: string | null;
          chairperson_designation: string | null;
          chairperson_master_type: string | null;
          hospital_id: string;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          type?: string;
          description?: string | null;
          meeting_frequency?: string;
          objectives?: string[] | null;
          min_meetings_required?: number;
          chairperson_id?: string | null;
          chairperson_name?: string | null;
          chairperson_designation?: string | null;
          chairperson_master_type?: string | null;
          hospital_id?: string;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          type?: string;
          description?: string | null;
          meeting_frequency?: string;
          objectives?: string[] | null;
          min_meetings_required?: number;
          chairperson_id?: string | null;
          chairperson_name?: string | null;
          chairperson_designation?: string | null;
          chairperson_master_type?: string | null;
          hospital_id?: string;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      committee_members: {
        Row: {
          id: string;
          committee_id: string;
          member_id: string;
          name: string;
          designation: string | null;
          department: string | null;
          role_in_committee: string;
          master_type: string | null;
          phone: string | null;
          is_active: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          committee_id: string;
          member_id: string;
          name: string;
          designation?: string | null;
          department?: string | null;
          role_in_committee?: string;
          master_type?: string | null;
          phone?: string | null;
          is_active?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          committee_id?: string;
          member_id?: string;
          name?: string;
          designation?: string | null;
          department?: string | null;
          role_in_committee?: string;
          master_type?: string | null;
          phone?: string | null;
          is_active?: boolean;
          created_at?: string;
        };
      };
      committee_meetings: {
        Row: {
          id: string;
          committee_id: string;
          meeting_date: string;
          agenda: string | null;
          minutes: string | null;
          attendees: string[] | null;
          decisions: string[] | null;
          action_items: string[] | null;
          next_meeting_date: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          committee_id: string;
          meeting_date: string;
          agenda?: string | null;
          minutes?: string | null;
          attendees?: string[] | null;
          decisions?: string[] | null;
          action_items?: string[] | null;
          next_meeting_date?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          committee_id?: string;
          meeting_date?: string;
          agenda?: string | null;
          minutes?: string | null;
          attendees?: string[] | null;
          decisions?: string[] | null;
          action_items?: string[] | null;
          next_meeting_date?: string | null;
          created_at?: string;
        };
      };
      departments: {
        Row: {
          id: string;
          dept_id: string;
          name: string;
          code: string;
          category: string;
          type: string;
          description: string | null;
          head_of_department: string | null;
          contact_number: string | null;
          nabh_is_active: boolean;
          nabh_last_audit_date: string | null;
          nabh_compliance_status: string;
          services: string[] | null;
          equipment_list: string[] | null;
          staff_count: number | null;
          is_emergency_service: boolean;
          operating_hours: string | null;
          hospital_id: string;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          dept_id: string;
          name: string;
          code: string;
          category: string;
          type: string;
          description?: string | null;
          head_of_department?: string | null;
          contact_number?: string | null;
          nabh_is_active?: boolean;
          nabh_last_audit_date?: string | null;
          nabh_compliance_status?: string;
          services?: string[] | null;
          equipment_list?: string[] | null;
          staff_count?: number | null;
          is_emergency_service?: boolean;
          operating_hours?: string | null;
          hospital_id?: string;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          dept_id?: string;
          name?: string;
          code?: string;
          category?: string;
          type?: string;
          description?: string | null;
          head_of_department?: string | null;
          contact_number?: string | null;
          nabh_is_active?: boolean;
          nabh_last_audit_date?: string | null;
          nabh_compliance_status?: string;
          services?: string[] | null;
          equipment_list?: string[] | null;
          staff_count?: number | null;
          is_emergency_service?: boolean;
          operating_hours?: string | null;
          hospital_id?: string;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      hospital_manuals: {
        Row: {
          id: string;
          title: string;
          description: string | null;
          category: string;
          version: string;
          author: string | null;
          department: string | null;
          created_date: string | null;
          last_updated: string | null;
          next_review_date: string | null;
          status: string;
          approved_by: string | null;
          file_url: string | null;
          file_size: string | null;
          page_count: number | null;
          nabh_relevant: boolean;
          nabh_standards: string[] | null;
          tags: string[] | null;
          review_frequency: string;
          documents_link: string | null;
          distribution_list: string[] | null;
          implementation_date: string | null;
          training_required: boolean;
          hospital_id: string;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          description?: string | null;
          category: string;
          version?: string;
          author?: string | null;
          department?: string | null;
          created_date?: string | null;
          last_updated?: string | null;
          next_review_date?: string | null;
          status?: string;
          approved_by?: string | null;
          file_url?: string | null;
          file_size?: string | null;
          page_count?: number | null;
          nabh_relevant?: boolean;
          nabh_standards?: string[] | null;
          tags?: string[] | null;
          review_frequency?: string;
          documents_link?: string | null;
          distribution_list?: string[] | null;
          implementation_date?: string | null;
          training_required?: boolean;
          hospital_id?: string;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          title?: string;
          description?: string | null;
          category?: string;
          version?: string;
          author?: string | null;
          department?: string | null;
          created_date?: string | null;
          last_updated?: string | null;
          next_review_date?: string | null;
          status?: string;
          approved_by?: string | null;
          file_url?: string | null;
          file_size?: string | null;
          page_count?: number | null;
          nabh_relevant?: boolean;
          nabh_standards?: string[] | null;
          tags?: string[] | null;
          review_frequency?: string;
          documents_link?: string | null;
          distribution_list?: string[] | null;
          implementation_date?: string | null;
          training_required?: boolean;
          hospital_id?: string;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      licenses: {
        Row: {
          id: string;
          name: string;
          category: string;
          license_number: string | null;
          issuing_authority: string | null;
          issue_date: string | null;
          expiry_date: string | null;
          validity_period: string | null;
          status: string;
          description: string | null;
          attached_document: string | null;
          renewal_process: string | null;
          responsible_person: string | null;
          reminder_days: number;
          last_renewal_date: string | null;
          renewal_cost: string | null;
          documents_link: string | null;
          hospital_id: string;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          category: string;
          license_number?: string | null;
          issuing_authority?: string | null;
          issue_date?: string | null;
          expiry_date?: string | null;
          validity_period?: string | null;
          status?: string;
          description?: string | null;
          attached_document?: string | null;
          renewal_process?: string | null;
          responsible_person?: string | null;
          reminder_days?: number;
          last_renewal_date?: string | null;
          renewal_cost?: string | null;
          documents_link?: string | null;
          hospital_id?: string;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          category?: string;
          license_number?: string | null;
          issuing_authority?: string | null;
          issue_date?: string | null;
          expiry_date?: string | null;
          validity_period?: string | null;
          status?: string;
          description?: string | null;
          attached_document?: string | null;
          renewal_process?: string | null;
          responsible_person?: string | null;
          reminder_days?: number;
          last_renewal_date?: string | null;
          renewal_cost?: string | null;
          documents_link?: string | null;
          hospital_id?: string;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
  };
}
